name: 01 - Building Blocks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Gurusundaram's First step
        run: |
          echo "I will sucess"
          echo "Guru is a devops Engg"
          exit 0

      - name: Guru became Expert
        run: echo "Guru started Rocking !"
